apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubepack-operator.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepack-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      serviceAccountName: {{ include "kubepack-operator.serviceAccountName" . }}
      containers:
      - name: kubectl
        image: {{ .Values.cleaner.registry }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}
        command:
          - sh
          - -c
          - "sleep 2; \
          kubectl delete validatingwebhookconfigurations validators.kubepack.com || true; \
          kubectl delete mutatingwebhookconfiguration mutators.kubepack.com || true; \
          kubectl delete apiservice v1alpha1.mutators.kubepack.com || true; \
          kubectl delete apiservice v1alpha1.validators.kubepack.com || true;"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Never
