apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubepack-operator.fullname" . }}
  labels:
    {{- include "kubepack-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubepack-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubepack-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
