apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubepack-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepack-operator.labels" . | nindent 4 }}
{{- if and (eq .Values.monitoring.agent "prometheus.io/builtin") .Values.monitoring.operator }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  selector:
    {{- include "kubepack-operator.selectorLabels" . | nindent 4 }}
