# GKE returns Major:"1", Minor:"10+"
{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.kubepack.com
  labels:
    {{- include "kubepack-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: applications.validators.kubepack.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.kubepack.com/v1alpha1/dashboardvalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
      - CREATE
      - UPDATE
    apiGroups:
      - kubepack.com
    apiVersions:
      - "*"
    resources:
      - applications
  failurePolicy: Fail
  {{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
  {{- end }}
{{ end }}
